services:
  # Backend API Service
  - type: web
    name: ticketsphere-api
    runtime: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
      - key: MONGODB_URI
        value: mongodb+srv://ticketsphere01_db_user:FnH1jzAOz5xIDA1u@ticketspherecluster.mcxvqml.mongodb.net/ticketsphere?retryWrites=true&w=majority&appName=TicketSphereCluster
      - key: JWT_SECRET
        value: 4f8b5c2a9d6e1f3a8b7c5d2e9f6a3b8c5d2e9f6a3b8c5d2e9f6a3b8c5d2e9f6a3b
      - key: JWT_EXPIRE
        value: 30d
      - key: FRONTEND_URL
        value: https://ticketsphere-frontend.onrender.com
      - key: UPI_ID
        value: 7362065730@ptsbi
      - key: MERCHANT_NAME
        value: TicketSphere
      - key: PAYMENT_GATEWAY_KEY
        value: rzp_live_1234567890
      - key: PAYMENT_GATEWAY_SECRET
        generateValue: true  # Auto-generate secure secret
      - key: FIREBASE_PROJECT_ID
        value: ticketsphere-0101
      - key: FIREBASE_PRIVATE_KEY_ID
        value: a1b2c3d4e5f6789012345678901234567890abcd
      - key: FIREBASE_PRIVATE_KEY
        value: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7VJTUt9Us8cKB\nUFOYcnV1X7o6zr5YGNtbzjUV4x4F8aQ3HnB5DcN7kP9sL2R1WqOm3YtX8eZ4cT\n... (Replace with actual Firebase private key)\n-----END PRIVATE KEY-----\n"
      - key: FIREBASE_CLIENT_EMAIL
        value: firebase-adminsdk-fbsvc@ticketsphere-0101.iam.gserviceaccount.com
      - key: FIREBASE_CLIENT_ID
        value: 123456789012345678901
      - key: FIREBASE_AUTH_URI
        value: https://accounts.google.com/o/oauth2/auth
      - key: FIREBASE_TOKEN_URI
        value: https://oauth2.googleapis.com/token
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        value: support@ticketsphere.com
      - key: EMAIL_PASS
        value: abcd_efgh_ijkl_mnop
    
  # Frontend Static Site Service
  - type: web
    name: ticketsphere-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://ticketsphere-api.onrender.com/api
      - key: VITE_FIREBASE_API_KEY
        value: AIzaSyBvOkBwN6Va2yxaRPcHcL9H_z_XgT0xLDU
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: ticketsphere-0101.firebaseapp.com
      - key: VITE_FIREBASE_PROJECT_ID
        value: ticketsphere-0101
      - key: VITE_FIREBASE_STORAGE_BUCKET
        value: ticketsphere-0101.appspot.com
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        value: 123456789012
      - key: VITE_FIREBASE_APP_ID
        value: 1:123456789012:web:abcdef1234567890abcdef
      - key: NODE_ENV
        value: production

# No external databases needed - using MongoDB Atlas
